# .github/workflows/hello-world.yml

name: Hello World Workflow

on: [push]  # This runs when you push to the repo

jobs:
  say_hello:
    runs-on: ubuntu-latest  # Run this job on a virtual machine with Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
